import { EntrepreneurDataType, InvestorDataType, CollaborationRequestDataType } from "@/types";

export const mockEntrepreneurs: EntrepreneurDataType = [
  {
    id: 1,
    name: "Sarah Johnson",
    email: "sarah@techstartup.com",
    phone: "+1-555-0101",
    startupName: "TechFlow Solutions",
    bio: "Passionate entrepreneur with 8 years of experience in fintech and blockchain technology.",
    startupDescription:
      "Revolutionary payment processing platform that reduces transaction fees by 40% using blockchain technology.",
    fundingNeed: "$2.5M",
    industry: "Fintech",
    location: "San Francisco, CA",
    website: "www.techflow.com",
    foundedYear: 2023,
    teamSize: 12,
    avatar:
      "https://images.unsplash.com/photo-1494790108755-2616b169a920?w=150&h=150&fit=crop&crop=faces",
  },
  {
    id: 2,
    name: "Marcus Rodriguez",
    email: "marcus@greentech.io",
    phone: "+1-555-0102",
    startupName: "GreenTech Innovations",
    bio: "Environmental engineer turned entrepreneur, focused on sustainable technology solutions.",
    startupDescription:
      "Developing smart solar panels with 35% higher efficiency and integrated IoT monitoring.",
    fundingNeed: "$5M",
    industry: "CleanTech",
    location: "Austin, TX",
    website: "www.greentech-innovations.com",
    foundedYear: 2022,
    teamSize: 18,
    avatar:
      "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop&crop=faces",
  },
  {
    id: 3,
    name: "Emily Chen",
    email: "emily@healthai.com",
    phone: "+1-555-0103",
    startupName: "HealthAI Diagnostics",
    bio: "Medical doctor and AI researcher specializing in diagnostic imaging and machine learning.",
    startupDescription:
      "AI-powered medical imaging platform that can detect diseases 3x faster than traditional methods.",
    fundingNeed: "$8M",
    industry: "HealthTech",
    location: "Boston, MA",
    website: "www.healthai-diagnostics.com",
    foundedYear: 2021,
    teamSize: 25,
    avatar:
      "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=150&h=150&fit=crop&crop=faces",
  },
  {
    id: 4,
    name: "David Kim",
    email: "david@edutech.co",
    phone: "+1-555-0104",
    startupName: "EduTech Connect",
    bio: "Former teacher with a passion for transforming education through technology.",
    startupDescription:
      "Interactive learning platform that adapts to individual student needs using AI.",
    fundingNeed: "$3M",
    industry: "EdTech",
    location: "Seattle, WA",
    website: "www.edutech-connect.com",
    foundedYear: 2023,
    teamSize: 8,
    avatar:
      "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop&crop=faces",
  },
  {
    id: 5,
    name: "Lisa Thompson",
    email: "lisa@foodtech.net",
    phone: "+1-555-0105",
    startupName: "FoodTech Labs",
    bio: "Food scientist and entrepreneur creating sustainable food solutions for the future.",
    startupDescription:
      "Plant-based protein alternatives that taste identical to meat with 80% less environmental impact.",
    fundingNeed: "$12M",
    industry: "FoodTech",
    location: "Portland, OR",
    website: "www.foodtech-labs.net",
    foundedYear: 2020,
    teamSize: 35,
    avatar:
      "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop&crop=faces",
  },
  {
    id: 6,
    name: "Ahmed Hassan",
    email: "ahmed@mobilefirst.com",
    phone: "+1-555-0106",
    startupName: "MobileFirst Solutions",
    bio: "Mobile app developer with expertise in cross-platform development and user experience.",
    startupDescription:
      "No-code mobile app builder that enables businesses to create professional apps in minutes.",
    fundingNeed: "$1.8M",
    industry: "SaaS",
    location: "Miami, FL",
    website: "www.mobilefirst-solutions.com",
    foundedYear: 2023,
    teamSize: 6,
    avatar:
      "https://images.unsplash.com/photo-1507591064344-4c6ce005b128?w=150&h=150&fit=crop&crop=faces",
  },
  {
    id: 7,
    name: "Jennifer Walsh",
    email: "jennifer@retailtech.io",
    phone: "+1-555-0107",
    startupName: "RetailTech Dynamics",
    bio: "Retail industry veteran with 15 years of experience in omnichannel commerce.",
    startupDescription:
      "AR-powered shopping experience that allows customers to try products virtually before buying.",
    fundingNeed: "$6M",
    industry: "RetailTech",
    location: "New York, NY",
    website: "www.retailtech-dynamics.io",
    foundedYear: 2022,
    teamSize: 22,
    avatar:
      "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=150&h=150&fit=crop&crop=faces",
  },
  {
    id: 8,
    name: "Robert Taylor",
    email: "robert@agritech.co",
    phone: "+1-555-0108",
    startupName: "AgriTech Innovations",
    bio: "Agricultural engineer focused on precision farming and sustainable agriculture practices.",
    startupDescription:
      "Drone-based crop monitoring system with AI analysis for optimized farming yields.",
    fundingNeed: "$4.5M",
    industry: "AgriTech",
    location: "Denver, CO",
    website: "www.agritech-innovations.co",
    foundedYear: 2021,
    teamSize: 14,
    avatar:
      "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=150&h=150&fit=crop&crop=faces",
  },
  {
    id: 9,
    name: "Priya Patel",
    email: "priya@cybersec.net",
    phone: "+1-555-0109",
    startupName: "CyberSecure Pro",
    bio: "Cybersecurity expert with experience in enterprise security and threat detection.",
    startupDescription:
      "AI-powered cybersecurity platform that predicts and prevents attacks before they happen.",
    fundingNeed: "$7M",
    industry: "Cybersecurity",
    location: "San Jose, CA",
    website: "www.cybersecure-pro.net",
    foundedYear: 2022,
    teamSize: 20,
    avatar:
      "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&h=150&fit=crop&crop=faces",
  },
  {
    id: 10,
    name: "Michael Brown",
    email: "michael@logisticsai.com",
    phone: "+1-555-0110",
    startupName: "LogisticsAI Systems",
    bio: "Supply chain expert with a vision to revolutionize logistics through artificial intelligence.",
    startupDescription:
      "Smart logistics platform that optimizes delivery routes and reduces shipping costs by 30%.",
    fundingNeed: "$9M",
    industry: "Logistics",
    location: "Chicago, IL",
    website: "www.logisticsai-systems.com",
    foundedYear: 2020,
    teamSize: 28,
    avatar:
      "https://images.unsplash.com/photo-1519244703995-f4e0f30006d5?w=150&h=150&fit=crop&crop=faces",
  },
  {
    id: 11,
    name: "Anna Kowalski",
    email: "anna@proptech.io",
    phone: "+1-555-0111",
    startupName: "PropTech Ventures",
    bio: "Real estate professional turned tech entrepreneur with focus on property technology.",
    startupDescription:
      "Virtual reality platform for remote property viewing and smart contract transactions.",
    fundingNeed: "$4M",
    industry: "PropTech",
    location: "Los Angeles, CA",
    website: "www.proptech-ventures.io",
    foundedYear: 2023,
    teamSize: 11,
    avatar:
      "https://images.unsplash.com/photo-1507591064344-4c6ce005b128?w=150&h=150&fit=crop&crop=faces",
  },
  {
    id: 12,
    name: "Carlos Martinez",
    email: "carlos@smartcity.tech",
    phone: "+1-555-0112",
    startupName: "SmartCity Technologies",
    bio: "Urban planner and tech innovator working on smart city infrastructure solutions.",
    startupDescription:
      "IoT-based smart city platform for traffic management and energy optimization.",
    fundingNeed: "$15M",
    industry: "Smart Cities",
    location: "Phoenix, AZ",
    website: "www.smartcity-tech.com",
    foundedYear: 2021,
    teamSize: 40,
    avatar:
      "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&h=150&fit=crop&crop=faces",
  },
  {
    id: 13,
    name: "Rachel Green",
    email: "rachel@beautytech.co",
    phone: "+1-555-0113",
    startupName: "BeautyTech Lab",
    bio: "Cosmetic chemist and entrepreneur revolutionizing the beauty industry with technology.",
    startupDescription:
      "AI-powered personalized skincare recommendations based on skin analysis and lifestyle.",
    fundingNeed: "$3.5M",
    industry: "BeautyTech",
    location: "Nashville, TN",
    website: "www.beautytech-lab.co",
    foundedYear: 2023,
    teamSize: 9,
    avatar:
      "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&h=150&fit=crop&crop=faces",
  },
  {
    id: 14,
    name: "James Wilson",
    email: "james@sportstech.net",
    phone: "+1-555-0114",
    startupName: "SportsTech Analytics",
    bio: "Former professional athlete turned entrepreneur, focusing on sports performance technology.",
    startupDescription:
      "Wearable technology for real-time sports performance analysis and injury prevention.",
    fundingNeed: "$5.5M",
    industry: "SportsTech",
    location: "Atlanta, GA",
    website: "www.sportstech-analytics.net",
    foundedYear: 2022,
    teamSize: 16,
    avatar:
      "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&h=150&fit=crop&crop=faces",
  },
  {
    id: 15,
    name: "Sophie Anderson",
    email: "sophie@traveltech.io",
    phone: "+1-555-0115",
    startupName: "TravelTech Collective",
    bio: "Travel industry expert with passion for sustainable and technology-driven travel solutions.",
    startupDescription:
      "AI travel companion that creates personalized sustainable travel itineraries.",
    fundingNeed: "$2M",
    industry: "TravelTech",
    location: "San Diego, CA",
    website: "www.traveltech-collective.io",
    foundedYear: 2023,
    teamSize: 7,
    avatar:
      "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&h=150&fit=crop&crop=faces",
  },
];

export const mockInvestors: InvestorDataType = [
  {
    id: 1,
    name: "Jonathan Sterling",
    email: "jonathan@sterlingvc.com",
    phone: "+1-555-1001",
    bio: "Seasoned venture capitalist with 20+ years of experience in early-stage technology investments.",
    investmentInterests: ["Fintech", "AI/ML", "Blockchain", "SaaS"],
    portfolioCompanies: ["TechCorp", "DataFlow", "CryptoBase", "CloudSync"],
    investmentRange: "$1M - $10M",
    location: "Palo Alto, CA",
    firm: "Sterling Venture Capital",
    website: "www.sterlingvc.com",
    yearsExperience: 22,
    totalInvestments: 85,
    avatar:
      "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop&crop=faces",
  },
  {
    id: 2,
    name: "Victoria Chang",
    email: "victoria@nexusangels.io",
    phone: "+1-555-1002",
    bio: "Angel investor and former tech executive specializing in healthcare and biotechnology startups.",
    investmentInterests: ["HealthTech", "BioTech", "MedTech", "AI in Healthcare"],
    portfolioCompanies: ["MedAI", "BioLabs", "HealthStream", "GeneTech"],
    investmentRange: "$500K - $5M",
    location: "Boston, MA",
    firm: "Nexus Angels",
    website: "www.nexusangels.io",
    yearsExperience: 15,
    totalInvestments: 42,
    avatar:
      "https://images.unsplash.com/photo-1494790108755-2616b169a920?w=150&h=150&fit=crop&crop=faces",
  },
  {
    id: 3,
    name: "Marcus Thompson",
    email: "marcus@greenventures.com",
    phone: "+1-555-1003",
    bio: "Impact investor focused on sustainable technology and clean energy solutions.",
    investmentInterests: ["CleanTech", "Renewable Energy", "Sustainability", "Green Technology"],
    portfolioCompanies: ["SolarMax", "WindTech", "EcoSolutions", "GreenGrid"],
    investmentRange: "$2M - $15M",
    location: "Portland, OR",
    firm: "Green Ventures Fund",
    website: "www.greenventures.com",
    yearsExperience: 18,
    totalInvestments: 38,
    avatar:
      "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop&crop=faces",
  },
  {
    id: 4,
    name: "Elena Rodriguez",
    email: "elena@techforward.vc",
    phone: "+1-555-1004",
    bio: "Former startup founder turned investor, passionate about supporting female entrepreneurs.",
    investmentInterests: ["EdTech", "FemTech", "E-commerce", "Social Impact"],
    portfolioCompanies: ["EduPlatform", "WomenHealth", "ShopSmart", "ImpactHub"],
    investmentRange: "$250K - $3M",
    location: "Austin, TX",
    firm: "TechForward VC",
    website: "www.techforward.vc",
    yearsExperience: 12,
    totalInvestments: 56,
    avatar:
      "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=150&h=150&fit=crop&crop=faces",
  },
  {
    id: 5,
    name: "David Kim",
    email: "david@alphapartners.net",
    phone: "+1-555-1005",
    bio: "Technology investor with deep expertise in enterprise software and cybersecurity.",
    investmentInterests: ["Cybersecurity", "Enterprise Software", "Cloud Computing", "DevOps"],
    portfolioCompanies: ["SecureNet", "CloudOps", "DataGuard", "TechShield"],
    investmentRange: "$1M - $8M",
    location: "Seattle, WA",
    firm: "Alpha Partners",
    website: "www.alphapartners.net",
    yearsExperience: 16,
    totalInvestments: 47,
    avatar:
      "https://images.unsplash.com/photo-1519244703995-f4e0f30006d5?w=150&h=150&fit=crop&crop=faces",
  },
  {
    id: 6,
    name: "Sarah Williams",
    email: "sarah@innovatecapital.com",
    phone: "+1-555-1006",
    bio: "Early-stage investor with a focus on disruptive consumer technology and mobile applications.",
    investmentInterests: ["Mobile Apps", "Consumer Tech", "Social Media", "Gaming"],
    portfolioCompanies: ["AppFlow", "SocialHub", "GameTech", "MobileFirst"],
    investmentRange: "$500K - $4M",
    location: "Los Angeles, CA",
    firm: "Innovate Capital",
    website: "www.innovatecapital.com",
    yearsExperience: 11,
    totalInvestments: 63,
    avatar:
      "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=150&h=150&fit=crop&crop=faces",
  },
  {
    id: 7,
    name: "Robert Johnson",
    email: "robert@meridianfund.io",
    phone: "+1-555-1007",
    bio: "Veteran investor specializing in B2B SaaS and enterprise automation solutions.",
    investmentInterests: [
      "B2B SaaS",
      "Enterprise Automation",
      "Workflow Management",
      "Productivity Tools",
    ],
    portfolioCompanies: ["WorkFlow", "AutoSuite", "ProductivePro", "EnterpriseAI"],
    investmentRange: "$2M - $12M",
    location: "New York, NY",
    firm: "Meridian Fund",
    website: "www.meridianfund.io",
    yearsExperience: 25,
    totalInvestments: 72,
    avatar:
      "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=150&h=150&fit=crop&crop=faces",
  },
  {
    id: 8,
    name: "Lisa Chen",
    email: "lisa@futuretech.vc",
    phone: "+1-555-1008",
    bio: "Technology investor focused on artificial intelligence and machine learning applications.",
    investmentInterests: ["Artificial Intelligence", "Machine Learning", "Computer Vision", "NLP"],
    portfolioCompanies: ["AIVision", "MLSystems", "SmartAnalytics", "NeuralNet"],
    investmentRange: "$1.5M - $10M",
    location: "San Francisco, CA",
    firm: "FutureTech Ventures",
    website: "www.futuretech.vc",
    yearsExperience: 14,
    totalInvestments: 39,
    avatar:
      "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop&crop=faces",
  },
  {
    id: 9,
    name: "Michael Davis",
    email: "michael@retailventures.com",
    phone: "+1-555-1009",
    bio: "Retail industry expert and investor focusing on e-commerce and retail technology innovations.",
    investmentInterests: ["E-commerce", "RetailTech", "Supply Chain", "Logistics"],
    portfolioCompanies: ["RetailPro", "ShopTech", "LogiFlow", "CommerceAI"],
    investmentRange: "$1M - $7M",
    location: "Chicago, IL",
    firm: "Retail Ventures",
    website: "www.retailventures.com",
    yearsExperience: 19,
    totalInvestments: 54,
    avatar:
      "https://images.unsplash.com/photo-1507591064344-4c6ce005b128?w=150&h=150&fit=crop&crop=faces",
  },
  {
    id: 10,
    name: "Amanda Foster",
    email: "amanda@healthfund.net",
    phone: "+1-555-1010",
    bio: "Healthcare investment specialist with background in medical technology and digital health.",
    investmentInterests: ["Digital Health", "Medical Devices", "Telemedicine", "Health Analytics"],
    portfolioCompanies: ["TeleMed", "HealthDevice", "MedAnalytics", "CareConnect"],
    investmentRange: "$2M - $15M",
    location: "Miami, FL",
    firm: "Health Innovation Fund",
    website: "www.healthfund.net",
    yearsExperience: 13,
    totalInvestments: 31,
    avatar:
      "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&h=150&fit=crop&crop=faces",
  },
  {
    id: 11,
    name: "Christopher Lee",
    email: "chris@mobilityvc.io",
    phone: "+1-555-1011",
    bio: "Transportation and mobility investor with expertise in autonomous vehicles and smart transportation.",
    investmentInterests: [
      "Autonomous Vehicles",
      "Smart Transportation",
      "Electric Vehicles",
      "Mobility as a Service",
    ],
    portfolioCompanies: ["AutoDrive", "SmartMove", "ElectricFlow", "MobilityHub"],
    investmentRange: "$3M - $20M",
    location: "Detroit, MI",
    firm: "Mobility Ventures",
    website: "www.mobilityvc.io",
    yearsExperience: 17,
    totalInvestments: 28,
    avatar:
      "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&h=150&fit=crop&crop=faces",
  },
  {
    id: 12,
    name: "Jennifer Park",
    email: "jennifer@propfund.com",
    phone: "+1-555-1012",
    bio: "Real estate technology investor specializing in PropTech and construction technology.",
    investmentInterests: [
      "PropTech",
      "Construction Tech",
      "Smart Buildings",
      "Real Estate Analytics",
    ],
    portfolioCompanies: ["BuildTech", "PropAnalytics", "SmartSpaces", "ConstructAI"],
    investmentRange: "$1M - $8M",
    location: "Denver, CO",
    firm: "Property Innovation Fund",
    website: "www.propfund.com",
    yearsExperience: 10,
    totalInvestments: 35,
    avatar:
      "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&h=150&fit=crop&crop=faces",
  },
  {
    id: 13,
    name: "Thomas Anderson",
    email: "thomas@agrifund.vc",
    phone: "+1-555-1013",
    bio: "Agricultural technology investor with background in farming and sustainable agriculture.",
    investmentInterests: [
      "AgriTech",
      "Precision Farming",
      "Food Technology",
      "Sustainable Agriculture",
    ],
    portfolioCompanies: ["FarmTech", "CropAI", "FoodInnovate", "AgriSmart"],
    investmentRange: "$2M - $12M",
    location: "Kansas City, MO",
    firm: "Agricultural Innovation Fund",
    website: "www.agrifund.vc",
    yearsExperience: 21,
    totalInvestments: 44,
    avatar:
      "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&h=150&fit=crop&crop=faces",
  },
  {
    id: 14,
    name: "Rachel Martinez",
    email: "rachel@entertaintech.com",
    phone: "+1-555-1014",
    bio: "Entertainment and media technology investor focusing on streaming, gaming, and content creation.",
    investmentInterests: ["Entertainment Tech", "Gaming", "Streaming", "Content Creation"],
    portfolioCompanies: ["StreamTech", "GameStudio", "ContentHub", "MediaFlow"],
    investmentRange: "$1M - $6M",
    location: "Las Vegas, NV",
    firm: "Entertainment Technology Fund",
    website: "www.entertaintech.com",
    yearsExperience: 9,
    totalInvestments: 41,
    avatar:
      "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&h=150&fit=crop&crop=faces",
  },
  {
    id: 15,
    name: "Kevin O'Brien",
    email: "kevin@spacefund.io",
    phone: "+1-555-1015",
    bio: "Space technology and aerospace investor with expertise in satellite technology and space exploration.",
    investmentInterests: ["Space Technology", "Satellites", "Aerospace", "Space Exploration"],
    portfolioCompanies: ["SpaceTech", "SatelliteNet", "AeroSpace", "OrbitSystems"],
    investmentRange: "$5M - $25M",
    location: "Houston, TX",
    firm: "Space Innovation Fund",
    website: "www.spacefund.io",
    yearsExperience: 15,
    totalInvestments: 22,
    avatar:
      "https://images.unsplash.com/photo-1519244703995-f4e0f30006d5?w=150&h=150&fit=crop&crop=faces",
  },
];

export const mockCollaborationRequests: CollaborationRequestDataType = [
  {
    id: 21,
    investorId: 1,
    entrepreneurId: 1,
    status: "pending",
    message:
      "Interested in learning more about your fintech solution. Would love to schedule a call.",
    createdAt: "2025-06-15T10:30:00Z",
  },
  {
    id: 22,
    investorId: 3,
    entrepreneurId: 3,
    status: "accepted",
    message: "Your AI diagnostic platform aligns perfectly with our healthcare investment thesis.",
    createdAt: "2025-06-14T14:20:00Z",
  },
  {
    id: 23,
    investorId: 4,
    entrepreneurId: 2,
    status: "pending",
    message:
      "Very impressed with your green technology approach. Let's discuss partnership opportunities.",
    createdAt: "2025-06-13T09:15:00Z",
  },
];
